// Generated by CoffeeScript 1.6.3
module.exports = function(req, callback) {
  var cand, favicon, htmlparser, parser, request, url;
  htmlparser = require("htmlparser2");
  url = require('url');
  request = require('request');
  favicon = {
    url: req,
    path: req
  };
  cand = '';
  parser = new htmlparser.Parser({
    onopentag: function(name, attr) {
      if (name === 'link' && (attr.rel === 'icon' || attr.rel === 'shortcut icon' || attr.type === 'image/x-icon')) {
        return cand = attr.href;
      }
    }
  });
  return request.get({
    uri: req,
    encoding: null
  }, function(err, res, body) {
    var guess, obj;
    if (err != null) {
      callback(err, null);
      return;
    }
    parser.write(body);
    parser.end();
    obj = url.parse(req);
    if (cand.length > 0) {
      if (cand.match(/[http|https]:\/\//)) {
        favicon.url = cand;
        return callback(null, favicon);
      } else {
        favicon.path = cand;
        if (cand.charAt(0) === '/') {
          favicon.url = "" + obj.protocol + "//" + obj.host + cand;
          return callback(null, favicon);
        } else {
          favicon.url = "" + obj.protocol + "//" + obj.host + "/" + cand;
          return callback(null, favicon);
        }
      }
    } else {
      guess = "" + obj.protocol + "//" + obj.host + "/favicon.ico";
      return request(guess, function(err, res, body) {
        if (res.statusCode === 200) {
          favicon.url = guess;
        }
        return callback(null, favicon);
      });
    }
  });
};
